jobs:
- name: check-pull-request
  plan:
  - get: pull-request
    trigger: true
    version: every

  - put: pull-request
    params:
      path: pull-request
      status: PENDING

  - task: lint
    image: hadolint
    config:
      inputs:
      - name: pull-request
        path: .
      platform: linux
      run:
        path: hadolint
        args:
        - Dockerfile
        - -t
        - warning

    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: FAILURE

  - put: pull-request
    params:
      path: pull-request
      status: SUCCESS

- name: build-tag
  plan:
  - in_parallel:
    - get: hadolint
    - get: source
    - get: version
      trigger: true

  - task: lint
    image: hadolint
    config:
      inputs:
      - name: source
        path: .
      platform: linux
      run:
        path: hadolint
        args:
        - Dockerfile
        - -t
        - warning

  - put: out-docker-image
    params:
      build: source
      cache: true
      cache_tag: latest
      dockerfile: source/Dockerfile
      tag_file: version/number
      tag_as_latest: true
    get_params: {skip_download: true}

- name: build-master
  plan:
  - in_parallel:
    - get: hadolint
    - get: debian
    - get: source
      trigger: true

  - task: lint
    image: hadolint
    config:
      inputs:
      - name: source
        path: .
      platform: linux
      run:
        path: hadolint
        args:
        - Dockerfile
        - -t
        - warning

  - task: docker-tag
    image: debian
    config:
      inputs:
      - name: source
        path: .
      outputs:
      - name: docker-tag
      platform: linux
      params:
        BRANCH: master
      run:
        path: bash
        args:
        - -c
        - |
          cat .git/refs/heads/${BRANCH} | cut -b1-8 > docker-tag/tag

  - put: out-docker-image
    params:
      build: source
      cache: true
      cache_tag: latest
      dockerfile: source/Dockerfile
      tag_file: docker-tag/tag
    get_params: {skip_download: true}

resources:
- name: version
  source:
    branch: master
    password: x-oauth-basic
    uri: https://github.com/yields-io/gh.git
    username: ((git-token.username))
  type: concourse-git-semver-tag

- icon: github
  name: source
  source:
    branch: master
    password: x-oauth-basic
    uri: https://github.com/yields-io/gh.git
    username: ((git-token.username))
  type: git

- name: out-docker-image
  type: docker-image
  source:
    username: ((docker.username))
    password:  ((docker.password))
    repository: build.yields.io/gh

- name: hadolint
  source:
    repository: hadolint/hadolint
  type: registry-image

- name: debian
  source:
    repository: debian
    tag: 11-slim
  type: registry-image

- name: pull-request
  type: pull-request
  source:
    repository: yields-io/gh
    access_token: ((git-token.username))

resource_types:
- name: concourse-git-semver-tag
  type: docker-image
  source:
    repository: laurentverbruggen/concourse-git-semver-tag-resource

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
